name: Github Pages Deploy

on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Install and build
        run: npm run build


      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # the branch the action deploys to
          folder: build # the folder the action should deploy